name: PR Auto-Approval

on:
  pull_request:
    branches:
      - main

jobs:
  approval-job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: |
          gh pr review ${{ github.event.pull_request.number }} -a -b "Auto-approved by Github Actions :rocket:" -R ${{ github.repository }}
        name: Auto-Approve PR ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ github.token }}
